sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdaterFast
    point_cloud_topic: /points2
    max_range: 1.1
    point_subsample: 1
    padding_offset: 0.05
    padding_scale: 1.2
    max_update_rate: 30.0
    filtered_cloud_topic: filtered_cloud
