sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdaterFast
    point_cloud_topic: /camera/depth/color/points
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 0.1
    max_update_rate: 0.0
    filtered_cloud_topic: filtered_cloud
